### ISSUE TITLE
All document store fail if body contain Contact

### ISSUE THREAD

**Issue by MilanPizem** [Majinko/Dataxer-Backend#18]
"error": "Internal Server Error",
    "message": "org.hibernate.TransientPropertyValueException: object references an unsaved transient instance - save the transient instance before flushing : com.data.dataxer.models.domain.Invoice.contact -> com.data.dataxer.models.domain.Contact; nested exception is java.lang.IllegalStateException: org.hibernate.TransientPropertyValueException: object references an unsaved transient instance - save the transient instance before flushing : com.data.dataxer.models.domain.Invoice.contact -> com.data.dataxer.models.domain.Contact"

```
{
    "title":"Test price offer",
    "number":"ZEL-123456789-FEN",
    "state":"APPROVED",
    "note":"Some text for noteing",
    "createdDate":"2020-09-17",
    "deliveredDate":"2020-10-16",
    "dueDate":"2020-10-16",
    "discount":"3000",
    "price":"18000",
    "totalPrice":"15000",
    "contact":{
        "name":"Lemon Russ",
        "street":"FenrisWolf",
        "city":"Fang",
        "country":"Fenris",
        "email":"spacewolfs@imperium.sm"
    }
}

**Comment by MilanPizem** [comment]
@Majinko 
contact objekt musi obsahovat `id` inac to failne -> je to takto ok?

**Comment by Majinko** [comment]
jasne ja ho tam vzdy posielam
