### ISSUE TITLE
Problem s ciselnikmi stale mam 2020100001 aj ked som vytvoril uz x faktur

### ISSUE THREAD

**Issue by Majinko** [Majinko/Dataxer-Backend#26]

**Comment by MilanPizem** [comment]
@Majinko 
Snazil som sa to nasimulovat ale ak pouzijem endpointy
localhost:8080/api/numberGenerator/generateAndSaveNextByType/PRICE_OFFER
localhost:8080/api/numberGenerator/generateAndSaveNextById/1
tak dostavam vzdy dalsie cislo.

Vies mi dat viac info ci pouzivas tieto endpointy pripadne ako vyzera ciselni v DB cokolvek?
